# Generated by Django 4.2.18 on 2025-01-16 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cabinets",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cabinetsId", models.IntegerField(verbose_name="location")),
                (
                    "cabinetAppointment",
                    models.TextField(max_length=30, verbose_name="appointment"),
                ),
                ("xCoord", models.IntegerField(default=0, verbose_name="x_coord")),
                ("yCoord", models.IntegerField(default=0, verbose_name="y_coord")),
            ],
        ),
        migrations.CreateModel(
            name="ErrorReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user", models.TextField(max_length=30, verbose_name="userName")),
                (
                    "description",
                    models.TextField(max_length=400, verbose_name="description"),
                ),
                (
                    "createdAt",
                    models.DateTimeField(auto_now_add=True, verbose_name="date"),
                ),
            ],
        ),
    ]
