# Generated by Django 4.2.18 on 2025-01-17 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("map", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="errorreport",
            name="is_fixed",
            field=models.BooleanField(default=False, verbose_name="BugFixed"),
        ),
        migrations.AlterField(
            model_name="errorreport",
            name="user",
            field=models.CharField(max_length=30, verbose_name="userName"),
        ),
    ]
