# Generated by Django 4.2.18 on 2025-01-19 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("map", "0002_errorreport_is_fixed_alter_errorreport_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cabinets",
            name="cabinetAppointment",
        ),
        migrations.AlterField(
            model_name="cabinets",
            name="cabinetsId",
            field=models.CharField(max_length=8, verbose_name="location"),
        ),
    ]
