# Generated by Django 4.2.18 on 2025-01-19 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("map", "0004_cabinets_cabinetsname"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cabinets",
            name="cabinetsName",
            field=models.CharField(max_length=6, verbose_name="name"),
        ),
    ]
