# Generated by Django 4.2.18 on 2025-01-26 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("map", "0005_alter_cabinets_cabinetsname"),
    ]

    operations = [
        migrations.AddField(
            model_name="errorreport",
            name="title",
            field=models.CharField(default=1, max_length=30, verbose_name="title"),
            preserve_default=False,
        ),
    ]
