# Generated by Django 5.1.5 on 2025-01-28 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("map", "0006_errorreport_title"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="errorreport",
            name="title",
        ),
    ]
