# Generated by Django 5.1.5 on 2025-02-02 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("map", "0007_remove_errorreport_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cabinets",
            name="cabinetsId",
            field=models.CharField(max_length=14, verbose_name="location"),
        ),
    ]
