# Generated by Django 5.1.5 on 2025-02-18 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("map", "0008_alter_cabinets_cabinetsid"),
    ]

    operations = [
        migrations.AddField(
            model_name="errorreport",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="error_reports/"),
        ),
        migrations.AlterField(
            model_name="cabinets",
            name="cabinetsId",
            field=models.CharField(max_length=8, verbose_name="location"),
        ),
        migrations.AlterField(
            model_name="cabinets",
            name="cabinetsName",
            field=models.CharField(max_length=14, verbose_name="name"),
        ),
    ]
